# fly.toml app configuration file generated for eternae-video-renderer on 2026-04-26T23:45:24-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eternae-video-renderer'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
